### ISSUE TITLE
Unknown AES key Get Key from Recovery

### ISSUE THREAD

**Issue by DragonsAndPostModernist** [bkerler/oppo_ozip_decrypt#1]
"Unknown AES key, reverse key from recovery first!"

Any idea how to obtain key from recovery?

**Comment by bkerler** [comment]
Just extract /sbin/recovery on a rooted device. Then you can find the aes key in the hex code nearby the string "read manifest". I suggest using radare2, ida, hopper or binja for reversing :) For some devices, the key is obfuscated, so you need to reverse the key using static analysis or debugging (f.e. frida).

**Comment by bkerler** [comment]
You can also extract the key from /vendor/lib64/libappypatch_jni.so, function aes_decrypt_file. The key should be labeled "userKey" and is refered by function aes_decrypt_file as arg3.

**Comment by RogueFendor** [comment]
Thanks really appreciated, this will keep me going for a while.

**Comment by AbShaheen184** [comment]
i am facing similar issue. "Unknown AES key, reverse key from recovery first!"
i don't have oppo phone. i just want to port some apps from oppo firmware. i am trying to decrypt cph1719 (Oppo r11s) firmware.

**Comment by bkerler** [comment]
Added r11s Keys as well :) Closing this issue.

**Comment by nouseforaname** [comment]
how would I get the keys on a r17 with locked BL and no Root? :)
