### ISSUE TITLE
Prerequirement oppo decrypt .ozip

### ISSUE THREAD

**Issue by haditriw** [bkerler/oppo_ozip_decrypt#11]
maybe I just added a suggestion prerequirement oppo decrypt.ozip
1. Use only python 3.6 (i used other version something said error)
2. 'pip install pycrypto' is not available, change to "pip install pycryptodome'

**Comment by aIecxs** [comment]
Python 3.7.3
`sudo pip3.7 install pycrypto`
Successfully installed pycrypto-2.6.1

**Comment by haditriw** [comment]
Because at tutorial said "pip install pycrypto" i think before, pycrypto doesnt work

**Comment by bkerler** [comment]
Actually, it doesn't really matter if you use pycryptodome or pycrypto. Both work fine. I will update the requirements.
