### ISSUE TITLE
Unknown aes key reverse key from recovery first

### ISSUE THREAD

**Issue by HELLXALPHA** [bkerler/oppo_ozip_decrypt#2]
Realme daughter company of oppo unlocked bl for realme 1 so inorder to work need to decrypt stock rom (cannot be rooted)  how to find aes key

**Comment by bkerler** [comment]
Can you upload aboot and recovery ?

**Comment by HELLXALPHA** [comment]
#ENDGAME:
https://drive.google.com/file/d/1X0mLCUPawHYCOo-F9mLceoSDPUJEeMgK/view?usp=drivesdk

**Comment by HELLXALPHA** [comment]
Recovery rename to .img

**Comment by bkerler** [comment]
It's at 0x217b78, just below the string "/data/system/meqn.dat". referenced from 0x1155b0 and 0x1155b4. Added to the repository.

**Comment by HELLXALPHA** [comment]
It works thanks
