### ISSUE TITLE
is there any way to descrypt realme X2 pro's ozip?

### ISSUE THREAD

**Issue by ShuosiWang** [bkerler/oppo_ozip_decrypt#28]
hi, is there any way to descrypt realme X2 pro's ozip?

**Comment by mauronofrio** [comment]
yes the key is the same of realme x, so the script is already able to decrypt it

**Comment by Honai1440** [comment]
is there any way to descrypt oppo k5's ozip?

**Comment by Honai1440** [comment]
> yes the key is the same of realme x, so the script is already able to decrypt it

hi, is there any way to descrypt oppo k5's ozip?
