### ISSUE TITLE
Boot.

### ISSUE THREAD

**Issue by sigitreal** [bkerler/oppo_ozip_decrypt#33]
![Screenshot_2020-01-01-13-56-57-88_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/57823488/71638892-c2084c00-2c9e-11ea-96af-e90f939759f1.png)
Help me... Im try to decrypt  boot.img on oppo k3, but this result..,.  Why? Im decrypt .ozip stockrom k3 is success.

**Comment by sigitreal** [comment]
Link stockrom oppo k3 http://downloads.oppo.com.s3.amazonaws.com/firmware/CPH1955%20%28K3%29/Mp4/CPH1955EX_11_OTA_0050_all_tafZl9hKq1So.ozip

**Comment by bkerler** [comment]
if you use it this way : ./ozipdecrypt.py ../CPH1955EX_11_OTA_0050_all_tafZl9hKq1So.ozip
you will get a file ./ozipdecrypt.py ../CPH1955EX_11_OTA_0050_all_tafZl9hKq1So.zip which will contain all decrypted data.
