### ISSUE TITLE
OTA decrypt all files inside ozip into folder preserving file names

### ISSUE THREAD

**Issue by aIecxs** [bkerler/oppo_ozip_decrypt#37]
there are encrypted files inside OTA zip we need to decrypt preserving original file names, for example

boot.img
dtbo.img
lk.img
md1img.img
preloader.img
preloader_emmc.img
preloader_ufs.img
scp.img
spmfw.img
sspm.img
system.transfer.list
tee.img
vbmeta.img
vendor.transfer.list

test file: [CPH1923EX_11_OTA_0210_all_8ZST9Bo4YLwc.ozip](https://androidfilehost.com/?fid=4349826312261615723)
~AES key: "1c4411a3a12533ae441b21bb31613c11", #A1k CPH1923~
edit: (key might wrong)
/sbin/recovery: [CPH1923_11_A.16_190430_88a6e79d_recovery_bin.zip](https://www.mediafire.com/file/61ez0dszp09jul1)
(extracted from full rom: [CPH1923_11_A.16_190430_88a6e79d.ofp](https://drive.google.com/file/d/1gsunEgws5AzRttjTNHVl7VmG-bOodbuT))

**Comment by bkerler** [comment]
Added key and fixed issue in commit 290d880
