### ISSUE TITLE
decryption of .ozip and .ofp firmware files.

### ISSUE THREAD

**Issue by techmashido** [bkerler/oppo_ozip_decrypt#4]
Dear sir,
Thanks for the reply and support via twitter and I have successfully converted ozip to zip with the help of your script. All thanks to you. :)

Regards

**Comment by Jwaleed8** [comment]
Please Add RealMe U1 (RMX1831) ozip extract

**Comment by bkerler** [comment]
can you send me the "/vendor/lib64/libapplypatch_jni.so" for that device ?

**Comment by Jwaleed8** [comment]
How to get it without root?

**Comment by Jwaleed8** [comment]
https://github.com/realme-kernel-opensource/RM1_AND_RMU1-kernel-source

Realme U1 (RMX1831) Device kernel Source

**Comment by Jwaleed8** [comment]
Here's The ozip Firmware

https://download.c.realme.com/osupdate/RMX1831EX_11_OTA_0070_all_UqwwgT6ye4J1.ozip

**Comment by bkerler** [comment]
adb pull isn't possible ? neither kernel source nor ozip will help

**Comment by bkerler** [comment]
Done. See full tutorial for it over here : https://bkerler.github.io/2019/04/the-game-begins/

**Comment by vishal12345678901234567890** [comment]
I want to convert my oppo f15 ozip to zip format please help me

**Comment by Facimilies** [comment]
hello, i have a realme x7 pro and need a flashable file. i have a ozip file but i need to be able to flash via sp flash tools, how can i get a scatter file ? or a OFP to convert to scatter file from a ozip firmware ? please any help would be appreciated i have hard bricked my phone. ozip link for correct firmware attached

RMX2121_11_OTA_0170_all_IrbQNx72829t.ozip ( please note the RMX2121_PU_11 is wrong firmware and cannot be flashed to my phone )

https://droidfilehost.com/download/realme-x7-pro-rmx2121-firmware-flash-file-stock-rom/?ind=1615834432477&filename=RMX2121_11_OTA_0190_all_B5cSIYs99RcD.ozip&wpdmdl=4242&refresh=6104fb82697e11627716482

**Comment by lakshywihdew** [comment]
Hello Please help i flashed a rom which was not compatible with my device... and now i cant flash any rom in twrp or any other recovery my device is realme 7 pro and i need to convert it into ofp file its zip right now
