### ISSUE TITLE
Unknown AES key

### ISSUE THREAD

**Issue by siddhrsh** [bkerler/oppo_ozip_decrypt#41]
I am trying to extract Realme C2 ozip to zip via ** --mode 2 command but i am getting unknown aes key reverse key from recovery first error first method works but i want to extract files in zip

**Comment by bkerler** [comment]
Please try the latest version

**Comment by siddhrsh** [comment]
> Please try the latest version

Tried with latest version same issue 
1st method working
2nd method gives Unknown AES key, reverse key from recovery first! error
can i extract file to twrp flashable zip directly because 1st method extract files in img format

**Comment by bkerler** [comment]
Added fixes in commit 91c717d. Please retry and report if it works. If it fails, please refer to the non-working ozip (full filename and/or link)

**Comment by tuyennn** [comment]
Here the log

`python ozipdecrypt.py .\RMX1801EX_11_OTA_0270_all_KvuheffUBmQD.ozip
Traceback (most recent call last):
  File "ozipdecrypt.py", line 20, in <module>
    from Crypto.Cipher import AES
ModuleNotFoundError: No module named 'Crypto'`

**Comment by siddhrsh** [comment]
> Added fixes in commit [91c717d](https://github.com/bkerler/oppo_ozip_decrypt/commit/91c717d6a6a5925a193c269e3b637f51b694ef4c). Please retry and report if it works. If it fails, please refer to the non-working ozip (full filename and/or link)
Thanks
its works but it extracted into img files is it possible to extract them in zip format

**Comment by bkerler** [comment]
Should be fixed in commit 8cc89cd
