### ISSUE TITLE
CPH1909 key incorrect?

### ISSUE THREAD

**Issue by describe19** [bkerler/oppo_ozip_decrypt#44]
I am trying to decrypt "CPH1909EX_11_OTA_0280_all_IFSiSfZdD2zH.ozip"
From here: https://oppo-ph.custhelp.com/app/software_update_detail/p_name/A5s

However the script says unknown AES key, despite there being CPH1909 key in the script.

Edit: I reverted to an older (the first 1909) commit and it worked. So I think something was broken recently.

Edit 2: reverting this in keytest: fixes it
Working line:
elif (dat[0:4] == b'\x41\x4E\x44\x52'):
Not working line:
elif (dat[0:4] == b'\x41\x56\x42\x30'):

**Comment by nathanvdh** [comment]
I tried to find the key myself, following your tutorial. But I'm stuck at 'stepping back in disassembly from one xref to another' I don't know what xrefs are and which ones I should be clicking and following.

**Comment by bkerler** [comment]
@nathanvdh : xrefs are references to a call (see ghidra/ida manual for details).

Tested and confirmed to work with commit 91c717d. Closing the issue.
