### ISSUE TITLE
Problem decrypting ozip

### ISSUE THREAD

**Issue by hbarsaiyan** [bkerler/oppo_ozip_decrypt#5]
My device is Realme 3 pro. I was trying to decrypt ozip (https://download.c.realme.com/osupdate/RMX1851EX_11_OTA_0120_all_L6ZahEviNKID.ozip) but /vendor/lib64/libapplypatch_jni.so does not exist in the device.

List of files in /vendor

/vendor:
app
bin
bt_firmware
dsp
etc
firmware_mnt
lib
lib64
lost+found
oppo
overlay
radio
rfs

/vendor/app:
ConnectionSecurityService
PowerOffAlarm
RfToolkit
SSGTelemetryService
TimeService
TrustZoneAccessService

/vendor/app/ConnectionSecurityService:
ConnectionSecurityService.apk

/vendor/app/PowerOffAlarm:
PowerOffAlarm.apk

/vendor/app/RfToolkit:
RfToolkit.apk
lib

/vendor/app/RfToolkit/lib:
arm64

/vendor/app/RfToolkit/lib/arm64:
libnativehelpers.so
liboddi.so
librftoolkit.so

/vendor/app/SSGTelemetryService:
SSGTelemetryService.apk

/vendor/app/TimeService:
TimeService.apk

/vendor/app/TrustZoneAccessService:
TrustZoneAccessService.apk

/vendor/bin:
acpi
base64
basename
blockdev
cal
cat
chcon
chgrp
chmod
chown
chroot
chrt
cksum
clear
cmp
comm
cp
cpio
cut
date
dd
df
diff
dirname
dmesg
dos2unix
du
echo
egrep
env
expand
expr
fallocate
false
fgrep
file
find
flock
fmt
free
getenforce
getevent
getprop
groups
gunzip
gzip
head
hostname
hw
hwclock
id
ifconfig
inotifyd
insmod
ionice
iorenice
kill
killall
ln
load_policy
log
logname
losetup
ls
lsmod
lsof
lspci
lsusb
md5sum
microcom
mkdir
mkfifo
mknod
mkswap
mktemp
modinfo
modprobe
more
mount
mountpoint
mv
netstat
newfs_msdos
nice
nl
nohup
od
paste
patch
pgrep
pidof
pkill
pmap
printenv
printf
ps
pwd
qmi-framework-tests
readlink
realpath
renice
restorecon
rm
rmdir
rmmod
runcon
sed
sendevent
seq
setenforce
setprop
setsid
sha1sum
sha224sum
sha256sum
sha384sum
sha512sum
sleep
sort
split
start
stat
stop
strings
stty
swapoff
swapon
sync
sysctl
tac
tail
tar
taskset
tee
time
timeout
top
touch
tr
true
truncate
tty
ulimit
umount
uname
uniq
unix2dos
uptime
usleep
uudecode
uuencode
vmstat
wc
which
whoami
xargs
xxd
yes
zcat

/vendor/bin/hw:

/vendor/bin/qmi-framework-tests:

/vendor/dsp:
adsp
cdsp
lost+found

/vendor/dsp/adsp:
AlacDecoderModule.so.1
ApeDecoderModule.so.1
AudioSphereModule.so.1
CFCMModule.so.1
CeltModule.so.1
EtsiAmrWbPlusDecModule.so.1
EtsiEaacPlusEncAndCmnModule.so.1
FlacDecoderModule.so.1
HeaacDecoderModule.so.1
LdacModule.so.1
MIC2AMBModule.so.1
SAPlusCmnModule.so.1
VorbisDecoderModule.so.1
WmaProDecoderModule.so.1
WmaStdDecoderModule.so.1
cellinfo_tools.so
chre_app_coverage.so
chre_app_coverage2.so
chre_app_oem.so
chre_app_sensor_cfg.so
chre_drv_bt.so
chre_drv_gf.so
chre_drv_loc.so
chre_drv_modem.so
chre_drv_wifi.so
chre_pal.so
fastrpc_shell_0
fluence_voiceplus_module.so.1
hbtpcfg_sdm670_800h_qhd.dat
hbtpcfg_sdm670_800s_fhd.dat
hbtpcfg_sdm670_801s_qhd.dat
libFastRPC_UTF_Forward_skel.so
libFastRPC_UTF_Forward_skel_pkt.so
libchre_slpi_skel.so
libstabilitydomain_skel.so
libsysmon_skel.so
libsysmondomain_skel.so
lowi_client.so
map_AVS_SHARED_LIBS_670.adsp.prodQ.txt
map_CHRE_SHARED_LIBS_670.adsp.prodQ.txt
map_SHARED_LIBS_670.adsp.prodQ.txt
mmecns_module.so.1
qtc800h.bin
qtc800s_dsp.bin
qtc801s.bin
sensor_testapp_40.so

/vendor/dsp/cdsp:
fastrpc_shell_3
libbenchmark_skel.so
libhcp_rpc_skel.so
libstabilitydomain_skel.so
libsysmon_skel.so
libsysmondomain_skel.so
libsysmonhvxthrottle_skel.so
libvpp_aie.so
libvpp_diagtools.so
libvpp_frc.so
libvpp_mvp.so
libvpp_nr.so
libvpp_qbr.so
libvpp_svc_skel.so
map_SHARED_LIBS_670.cdsp.prodQ.txt
ubwcdma_dynlib.so

/vendor/etc:
18041
18081
18097
18181
18385
18397
18621
IPACM_cfg.xml
M_Liveness_Antispoofing_General_full_snpe.model
M_Verify_MimicRes_Common_snpe.model
NOTICE.xml.gz
OPPO_OLED_AD_calib.cfg
a2dp_audio_policy_configuration.xml
acdbdata
apdr.conf
asd
audio
audio_effects.conf
audio_effects.xml
audio_output_policy.conf
audio_platform_info.xml
audio_platform_info_i2s.xml
audio_platform_info_intcodec.xml
audio_platform_info_oppo.xml
audio_platform_info_oppo_int_codec.xml
audio_platform_info_skuw.xml
audio_policy_configuration.xml
audio_policy_volumes.xml
audio_tuning_mixer.txt
audio_tuning_mixer_tasha.txt
audio_tuning_mixer_tavil.txt
camera
cne
data
default_volume_tables.xml
dirac
facepp
flp.conf
fs_config_dirs
fs_config_files
fstab-wlan.qcom
fstab.qcom
ftm_test_config
ftm_test_config_sdm710-skuw-snd-card
ftm_test_config_sdm710-tasha-snd-card
ftm_test_config_sdm710-tavil-snd-card
gpfspath_oem_config.xml
gps.conf
graphite_ipc_platform_info.xml
group
init
izat.conf
license.lic
listen_platform_info.xml
lm
media_codecs.xml
media_codecs_ffmpeg.xml
media_codecs_google_audio.xml
media_codecs_google_telephony.xml
media_codecs_google_video.xml
media_codecs_google_video_le.xml
media_codecs_oppo_performance.xml
media_codecs_oppo_video.xml
media_codecs_performance.xml
media_codecs_performance_sdm710_v0.xml
media_codecs_sdm710_v0.xml
media_codecs_vendor.xml
media_codecs_vendor_audio.xml
media_profiles.xml
media_profiles_V1_0.xml
media_profiles_vendor.xml
mixer_paths.xml
mixer_paths_18621.xml
mixer_paths_360cam.xml
mixer_paths_i2s.xml
mixer_paths_mtp.xml
mixer_paths_skuw.xml
mixer_paths_tasha.xml
mixer_paths_tashalite.xml
mixer_paths_tavil.xml
mkshrc
msm_irqbalance.conf
passwd
perf
permissions
powerhint.xml
project_info.txt
public.libraries.txt
qdcm_calib_data_Dual_nt35597_video_mode_dsi_truly_panel_without_DSC.xml
qdcm_calib_data_nt35597_cmd_mode_dsi_truly_panel_with_DSC.xml
qdcm_calib_data_oppo18081samsung_ams641rw01_1080_2340_cmd_mode_dsi_panel.xml
qdcm_calib_data_oppo18621_hx83112a_1080_2340_video_mode_dsi_panel.xml
qti_fp
r_submix_audio_policy_configuration.xml
sap.conf
scve
sec_config
seccomp_policy
security
self_init_config
selinux
sensors
sound_trigger_mixer_paths.xml
sound_trigger_mixer_paths_skuw.xml
sound_trigger_mixer_paths_wcd9335.xml
sound_trigger_mixer_paths_wcd9340.xml
sound_trigger_platform_info.xml
system_properties.xml
thermal-engine.conf
usb_audio_policy_configuration.xml
vintf
wifi
xtwifi.conf

/vendor/etc/18041:
audio_policy_configuration.xml
audio_policy_volumes.xml
default_volume_tables.xml

/vendor/etc/18081:
audio_policy_configuration.xml
audio_policy_volumes.xml
default_volume_tables.xml

/vendor/etc/18097:
audio_policy_configuration.xml
audio_policy_volumes.xml
default_volume_tables.xml

/vendor/etc/18181:
audio_policy_configuration.xml
audio_policy_volumes.xml
default_volume_tables.xml

/vendor/etc/18385:
audio_policy_configuration.xml
audio_policy_volumes.xml
default_volume_tables.xml

/vendor/etc/18397:
audio_policy_configuration.xml
audio_policy_volumes.xml
default_volume_tables.xml

/vendor/etc/18621:
audio_policy_configuration.xml
audio_policy_volumes.xml
default_volume_tables.xml

/vendor/etc/acdbdata:
18621
MTP
QRD
adsp_avs_config.acdb

/vendor/etc/acdbdata/18621:
Bluetooth_cal.acdb
General_cal.acdb
Global_cal.acdb
Handset_cal.acdb
Hdmi_cal.acdb
Headset_cal.acdb
Speaker_cal.acdb

/vendor/etc/acdbdata/MTP:
MTP_Bluetooth_cal.acdb
MTP_General_cal.acdb
MTP_Global_cal.acdb
MTP_Handset_cal.acdb
MTP_Hdmi_cal.acdb
MTP_Headset_cal.acdb
MTP_Speaker_cal.acdb
MTP_workspaceFile.qwsp
sdm670-tasha-snd-card
sdm670-tavil-snd-card

/vendor/etc/acdbdata/MTP/sdm670-tasha-snd-card:
MTP_WCD9335_Bluetooth_cal.acdb
MTP_WCD9335_General_cal.acdb
MTP_WCD9335_Global_cal.acdb
MTP_WCD9335_Handset_cal.acdb
MTP_WCD9335_Hdmi_cal.acdb
MTP_WCD9335_Headset_cal.acdb
MTP_WCD9335_Speaker_cal.acdb
MTP_WCD9335_workspaceFile.qwsp

/vendor/etc/acdbdata/MTP/sdm670-tavil-snd-card:
MTP_WCD9340_Bluetooth_cal.acdb
MTP_WCD9340_Codec_cal.acdb
MTP_WCD9340_General_cal.acdb
MTP_WCD9340_Global_cal.acdb
MTP_WCD9340_Handset_cal.acdb
MTP_WCD9340_Hdmi_cal.acdb
MTP_WCD9340_Headset_cal.acdb
MTP_WCD9340_Speaker_cal.acdb
MTP_WCD9340_workspaceFile.qwsp

/vendor/etc/acdbdata/QRD:
sdm670-skuw-snd-card

/vendor/etc/acdbdata/QRD/sdm670-skuw-snd-card:
QRD_SKUW_Bluetooth_cal.acdb
QRD_SKUW_General_cal.acdb
QRD_SKUW_Global_cal.acdb
QRD_SKUW_Handset_cal.acdb
QRD_SKUW_Hdmi_cal.acdb
QRD_SKUW_Headset_cal.acdb
QRD_SKUW_Speaker_cal.acdb
QRD_SKUW_workspaceFile.qwsp

/vendor/etc/asd:
class.dlc
detect.dlc

/vendor/etc/audio:
audio_policy_configuration.xml

/vendor/etc/camera:
Charming.cng
M_Verify_Faster_Common_4.0.0_wp.model
attribute.model
faceTpl0.rgb32
faceTpl1.rgb32
gasryuv.model
license.lic
oppo_camera_config.xml
skinSeg.model
vidhance_calibration

/vendor/etc/cne:
wqeclient

/vendor/etc/cne/wqeclient:
ATT
ROW
VZW

/vendor/etc/cne/wqeclient/ATT:
ATT_profile1.xml
ATT_profile2.xml
ATT_profile3.xml
ATT_profile4.xml
ATT_profile5.xml
ATT_profile6.xml

/vendor/etc/cne/wqeclient/ROW:
ROW_profile1.xml
ROW_profile15.xml
ROW_profile16.xml
ROW_profile17.xml
ROW_profile18.xml
ROW_profile19.xml
ROW_profile2.xml
ROW_profile20.xml
ROW_profile21.xml
ROW_profile3.xml
ROW_profile32.xml
ROW_profile4.xml
ROW_profile5.xml
ROW_profile6.xml
ROW_profile7.xml

/vendor/etc/cne/wqeclient/VZW:
VZW_profile1.xml
VZW_profile2.xml
VZW_profile3.xml
VZW_profile4.xml
VZW_profile5.xml
VZW_profile6.xml

/vendor/etc/data:
dsi_config.xml
netmgr_config.xml

/vendor/etc/dirac:
diracvdd.bin

/vendor/etc/facepp:
algo_cache_sdm710
human_model_image
opencl_model_cache_sdm710
relight

/vendor/etc/init:
android.hardware.audio@2.0-service.rc
android.hardware.bluetooth@1.0-service-qti.rc
android.hardware.camera.provider@2.4-service.rc
android.hardware.cas@1.0-service.rc
android.hardware.configstore@1.1-service.rc
android.hardware.drm@1.0-service.rc
android.hardware.drm@1.1-service.clearkey.rc
android.hardware.drm@1.1-service.widevine.rc
android.hardware.gatekeeper@1.0-service-qti.rc
android.hardware.graphics.composer@2.1-service.rc
android.hardware.health@2.0-service.rc
android.hardware.keymaster@4.0-service-qti.rc
android.hardware.light@2.0-service.rc
android.hardware.media.omx@1.0-service.rc
android.hardware.memtrack@1.0-service.rc
android.hardware.neuralnetworks@1.1-service-qti.rc
android.hardware.power@1.0-service.rc
android.hardware.sensors@1.0-service.rc
android.hardware.thermal@1.0-service.rc
android.hardware.usb@1.0-service.rc
android.hardware.vibrator@1.0-service.rc
android.hardware.wifi@1.0-service.rc
com.qualcomm.qti.wifidisplayhal@1.0-service.rc
hostapd.android.rc
hw
init.qti.fm.rc
init_qfp_daemon.rc
manifest_sku.rc
qcrild.rc
self-init.rc
vendor.display.color@1.0-service.rc
vendor.oppo.engnative.engineer@1.0-service.rc
vendor.oppo.engnative.engsensor@1.0-service.rc
vendor.oppo.engnative.messager@1.0-service.rc
vendor.oppo.hardware.biometrics.face@1.0-service.rc
vendor.oppo.hardware.biometrics.fingerprint@2.1-service.rc
vendor.oppo.hardware.biometrics.fingerprintpay@1.0-service.rc
vendor.oppo.hardware.camera.oppoAlgoProcessService@1.0-service.rc
vendor.oppo.hardware.cryptoeng@1.0-service.rc
vendor.oppo.hardware.hypnus@1.0-service.rc
vendor.oppo.hardware.ktv@1.0-service.rc
vendor.oppo.hardware.mmdisplayfeature@1.0-service.rc
vendor.oppo.hardware.oiface@1.0-service.rc
vendor.oppo.wifi.sniffer@1.0-service.rc
vendor.qti.esepowermanager@1.0-service.rc
vendor.qti.gnss@1.2-service.rc
vendor.qti.hardware.alarm@1.0-service.rc
vendor.qti.hardware.display.allocator@1.0-service.rc
vendor.qti.hardware.factory@1.0-service.rc
vendor.qti.hardware.perf@1.0-service.rc
vendor.qti.hardware.qdutils_disp@1.0-service-qti.rc
vendor.qti.hardware.qteeconnector@1.0-service.rc
vendor.qti.hardware.sensorscalibrate@1.0-service.rc
vendor.qti.hardware.soter@1.0-service.rc
vendor.qti.hardware.tui_comm@1.0-service-qti.rc
vendor.qti.secure_element@1.0-service.rc
vendor_engineermode.rc
vendor_transfer.rc
vndservicemanager.rc

/vendor/etc/init/hw:
init.msm.usb.configfs.rc
init.oppo.debug.diag.rc
init.oppo.reserve.rc
init.oppo.sensor.rc
init.oppo.vendor.fingerprint.rc
init.oppo.vendor.motor.rc
init.qcom.factory.rc
init.qcom.rc
init.qcom.usb.rc
init.target.rc
init.wlan.qcom.rc
init.wlan.target.rc

/vendor/etc/lm:
AdaptLaunchFeature.xml

/vendor/etc/perf:
commonresourceconfigs.xml
perfboostsconfig.xml
targetconfig.xml
targetresourceconfigs.xml

/vendor/etc/permissions:
android.hardware.bluetooth.xml
android.hardware.bluetooth_le.xml
android.hardware.camera.flash-autofocus.xml
android.hardware.camera.front.xml
android.hardware.camera.full.xml
android.hardware.camera.raw.xml
android.hardware.light.xml
android.hardware.location.gps.xml
android.hardware.opengles.aep.xml
android.hardware.sensor.accelerometer.xml
android.hardware.sensor.ambient_temperature.xml
android.hardware.sensor.barometer.xml
android.hardware.sensor.compass.xml
android.hardware.sensor.gyroscope.xml
android.hardware.sensor.hifi_sensors.xml
android.hardware.sensor.light.xml
android.hardware.sensor.proximity.xml
android.hardware.sensor.relative_humidity.xml
android.hardware.sensor.stepcounter.xml
android.hardware.sensor.stepdetector.xml
android.hardware.telephony.cdma.xml
android.hardware.telephony.gsm.xml
android.hardware.touchscreen.multitouch.jazzhand.xml
android.hardware.usb.accessory.xml
android.hardware.usb.host.xml
android.hardware.vulkan.compute-0.xml
android.hardware.vulkan.level-1.xml
android.hardware.vulkan.version-1_1.xml
android.hardware.wifi.direct.xml
android.hardware.wifi.xml
android.software.midi.xml
android.software.sip.voip.xml
handheld_core_hardware.xml
qti_fingerprint_interface.xml
vendor-oppo-engnative-engineer.xml
vendor-oppo-hardware.biometrics.fingerprintpay.xml
vendor-oppo-hardware.cryptoeng.xml
vendor-qti-hardware-sensorscalibrate.xml
vendor.qti.hardware.factory.xml

/vendor/etc/qti_fp:
image_quality
wakeup

/vendor/etc/qti_fp/image_quality:
templates

/vendor/etc/qti_fp/image_quality/templates:
double_fan_target_3_6
double_fan_target_4_2
fan_target
slanted_target

/vendor/etc/qti_fp/image_quality/templates/double_fan_target_3_6:
template1.pgm
template2.pgm
template3.pgm
template4.pgm

/vendor/etc/qti_fp/image_quality/templates/double_fan_target_4_2:
template1.pgm
template2.pgm
template3.pgm
template4.pgm

/vendor/etc/qti_fp/image_quality/templates/fan_target:
template1.pgm
template2.pgm
template3.pgm
template4.pgm

/vendor/etc/qti_fp/image_quality/templates/slanted_target:
template1.pgm
template2.pgm
template3.pgm
template4.pgm

/vendor/etc/qti_fp/wakeup:
templates

/vendor/etc/qti_fp/wakeup/templates:
template_imaginary.bin
template_real.bin

/vendor/etc/scve:
facereco

/vendor/etc/scve/facereco:
gModel.dat

/vendor/etc/seccomp_policy:
configstore@1.1.policy
mediacodec.policy
mediaextractor.policy

/vendor/etc/security:
ck.fs
pl.fs

/vendor/etc/self_init_config:
common

/vendor/etc/self_init_config/common:
self_init_config.xml

/vendor/etc/selinux:
plat_pub_versioned.cil
plat_pub_versioned_debug.cil
plat_sepolicy_vers.txt
precompiled_sepolicy
precompiled_sepolicy.plat_and_mapping.sha256
precompiled_sepolicy_debug
precompiled_sepolicy_debug.plat_and_mapping.sha256
vendor_file_contexts
vendor_hwservice_contexts
vendor_mac_permissions.xml
vendor_property_contexts
vendor_seapp_contexts
vendor_sepolicy.cil
vendor_sepolicy_debug.cil
vndservice_contexts

/vendor/etc/sensors:
config
hals.conf
sns_reg_config

/vendor/etc/sensors/config:
ak991x_dri_0.json
bmi160_0.json
default_sensors.json
devinfo_0.json
icp101xx_0.json
mmc5603nj_0.json
sdm710_ak991x_0.json
sdm710_bmi160_0.json
sdm710_irq.json
sdm710_mmc5603nj_0.json
sdm710_power_0.json
sdm710_stk3x3x_0.json
sdm710_tsl2540_0.json
sns_amd.json
sns_amd_sw_disabled.json
sns_amd_sw_enabled.json
sns_aont.json
sns_basic_gestures.json
sns_ccd.json
sns_cm.json
sns_dae.json
sns_device_orient.json
sns_diag_filter.json
sns_distance_bound.json
sns_dpc.json
sns_facing.json
sns_fmv.json
sns_geomag_rv.json
sns_gyro_cal.json
sns_mag_cal.json
sns_multishake.json
sns_pedometer.json
sns_rmd.json
sns_rotv.json
sns_smd.json
sns_tilt.json
sns_tilt_sw_disabled.json
sns_tilt_sw_enabled.json
sns_tilt_to_wake.json
stk3x3x_0.json
tsl2540_0.json

/vendor/etc/vintf:
compatibility_matrix.xml
manifest.xml

/vendor/etc/wifi:
WCNSS_qcom_cfg.ini
WCNSS_qcom_cfg_cmcc.ini
aoa_cldb_falcon.bin
aoa_cldb_swl14.bin
bdwlan_18041_id1.bin
bdwlan_18081_id1.bin
bdwlan_18081_id2.bin
bdwlan_18081_id3.bin
bdwlan_18081_id4.bin
bdwlan_18097_id1.bin
bdwlan_18097_id2.bin
bdwlan_18181_id1.bin
bdwlan_18181_id2.bin
bdwlan_18181_id3.bin
bdwlan_18181_id4.bin
bdwlan_18381_id1.bin
bdwlan_18381_id2.bin
bdwlan_18381_id3.bin
bdwlan_18381_id4.bin
bdwlan_18385_id1.bin
bdwlan_18385_id2.bin
bdwlan_18385_id3.bin
bdwlan_18385_id4.bin
bdwlan_18397_id1.bin
bdwlan_18539.bin
bdwlan_18621_id1.bin
bdwlan_18621_id1_mp.bin
bdwlan_18621_id2.bin
bdwlan_18621_id2_mp.bin
bdwlan_18621_id3.bin
bdwlan_18621_id3_mp.bin
bdwlan_18621_id4.bin
bdwlan_18621_id4_mp.bin
bdwlan_18621_id5.bin
bdwlan_18621_id5_mp.bin
bdwlan_18637.bin
bdwlan_18637_mp.bin
bdwlan_18638.bin
bdwlan_18638_mp.bin
bin_version
bin_version_realme
fstman.ini
p2p_supplicant_overlay.conf
sar-vendor-cmd.xml
wifi_concurrency_cfg.txt
wigig_p2p_supplicant.conf
wigig_supplicant.conf
wpa_supplicant.conf
wpa_supplicant_overlay.conf

/vendor/lib:
camera
dsp
egl
hw
libCB.so
libEGL_adreno.so
libGLESv2_adreno.so
libOpenCL.so
libOppoAPSMemMgr.so
libOppoAlgoClient.so
libRSDriver_adreno.so
libadreno_utils.so
libadsprpc.so
libbccQTI.so
libcdsprpc.so
libdiag.so
libdrm.so
libdrmutils.so
libfastcvdsp_stub.so
libfastcvopt.so
libgralloccore.so
libgrallocutils.so
libgsl.so
liblistenjni.so
liblistensoundmodel2.so
libllvm-glnext.so
libllvm-qcom.so
libnativehelpers.so
liboddi.so
libq3dtools_adreno.so
libqdMetaData.so
libqdutils.so
libqservice.so
libqti-perfd-client.so
librftoolkit.so
librs_adreno.so
librs_adreno_sha1.so
libsdsprpc.so
libtime_genoff.so
mediacas
mediadrm
modules
qcdrm
rfsa
soundfx
vendor.oppo.hardware.camera.oppoAlgoProcessService@1.0.so
vendor.qti.hardware.perf@1.0.so
vndk

/vendor/lib/camera:
components

/vendor/lib/camera/components:

/vendor/lib/dsp:

/vendor/lib/egl:
eglSubDriverAndroid.so
libEGL_adreno.so
libGLESv1_CM_adreno.so
libGLESv2_adreno.so
libQTapGLES.so
libq3dtools_adreno.so
libq3dtools_esx.so

/vendor/lib/hw:
android.hardware.graphics.mapper@2.0-impl-qti-display.so
android.hardware.renderscript@1.0-impl.so
gralloc.default.so
gralloc.sdm710.so
vulkan.sdm710.so

/vendor/lib/mediacas:

/vendor/lib/mediadrm:

/vendor/lib/modules:

/vendor/lib/qcdrm:
playready

/vendor/lib/qcdrm/playready:
lib

/vendor/lib/qcdrm/playready/lib:
mediadrm

/vendor/lib/qcdrm/playready/lib/mediadrm:

/vendor/lib/rfsa:
adsp

/vendor/lib/rfsa/adsp:

/vendor/lib/soundfx:

/vendor/lib/vndk:

/vendor/lib64:
camera
egl
hw
libCB.so
libEGL_adreno.so
libGLESv2_adreno.so
libOpenCL.so
libRSDriver_adreno.so
libadreno_utils.so
libadsprpc.so
libbccQTI.so
libcdsprpc.so
libdiag.so
libdrm.so
libdrmutils.so
libfastcvdsp_stub.so
libfastcvopt.so
libgralloccore.so
libgrallocutils.so
libgsl.so
liblistenjni.so
liblistensoundmodel2.so
libllvm-glnext.so
libllvm-qcom.so
libnativehelpers.so
liboddi.so
libq3dtools_adreno.so
libqdMetaData.so
libqdutils.so
libqservice.so
libqti-perfd-client.so
librftoolkit.so
librs_adreno.so
librs_adreno_sha1.so
libsdsprpc.so
libtime_genoff.so
mediacas
mediadrm
rfsa
soundfx
vendor.qti.hardware.perf@1.0.so

/vendor/lib64/camera:

/vendor/lib64/egl:
eglSubDriverAndroid.so
libEGL_adreno.so
libGLESv1_CM_adreno.so
libGLESv2_adreno.so
libQTapGLES.so
libq3dtools_adreno.so
libq3dtools_esx.so

/vendor/lib64/hw:
android.hardware.graphics.mapper@2.0-impl-qti-display.so
android.hardware.renderscript@1.0-impl.so
gralloc.default.so
gralloc.sdm710.so
vulkan.sdm710.so

/vendor/lib64/mediacas:

/vendor/lib64/mediadrm:

/vendor/lib64/rfsa:
adsp

/vendor/lib64/rfsa/adsp:

/vendor/lib64/soundfx:

/vendor/oppo:

/vendor/overlay:
BluetoothResCommon.apk
CarrierConfigResCommon.apk
CellBroadcastReceiverResCommon.apk
ChinaMobileFrameworksRes
CmccMmsRes.apk
CmccSettingsTheme
CmccSystemUIRes.apk
CtFrameworksTheme
CtNetworkSettingRes
CtSystemUITheme
DisplayCutoutEmulationCorner
DisplayCutoutEmulationDouble
DisplayCutoutEmulationTall
FrameworksResCommon.apk
FrameworksResTarget.apk
OptInAppOverlay
SystemUIResCommon.apk
SysuiDarkTheme
TelecommResCommon.apk
TelephonyResCommon.apk

/vendor/overlay/ChinaMobileFrameworksRes:
ChinaMobileFrameworksRes.apk

/vendor/overlay/CmccSettingsTheme:
CmccSettingsRes.apk

/vendor/overlay/CtFrameworksTheme:
CtFrameworksRes.apk

/vendor/overlay/CtNetworkSettingRes:
CtNetworkSettingRes.apk

/vendor/overlay/CtSystemUITheme:
CtSystemUIRes.apk

/vendor/overlay/DisplayCutoutEmulationCorner:
DisplayCutoutEmulationCornerOverlay.apk

/vendor/overlay/DisplayCutoutEmulationDouble:
DisplayCutoutEmulationDoubleOverlay.apk

/vendor/overlay/DisplayCutoutEmulationTall:
DisplayCutoutEmulationTallOverlay.apk

/vendor/overlay/OptInAppOverlay:
OptInAppOverlay.apk

/vendor/overlay/SysuiDarkTheme:
SysuiDarkThemeOverlay.apk

/vendor/radio:
qcril_database

/vendor/radio/qcril_database:
upgrade

/vendor/radio/qcril_database/upgrade:

/vendor/rfs:
apq
mdm
msm

/vendor/rfs/apq:
gnss

/vendor/rfs/apq/gnss:
hlos
ramdumps
readonly
readwrite
shared

/vendor/rfs/apq/gnss/readonly:
firmware
vendor

/vendor/rfs/apq/gnss/readonly/vendor:
firmware

/vendor/rfs/mdm:
adsp
cdsp
mpss
slpi
tn

/vendor/rfs/mdm/adsp:
hlos
ramdumps
readonly
readwrite
shared

/vendor/rfs/mdm/adsp/readonly:
firmware
vendor

/vendor/rfs/mdm/adsp/readonly/vendor:
firmware

/vendor/rfs/mdm/cdsp:
hlos
ramdumps
readonly
readwrite
shared

/vendor/rfs/mdm/cdsp/readonly:
firmware

/vendor/rfs/mdm/mpss:
hlos
ramdumps
readonly
readwrite
shared

/vendor/rfs/mdm/mpss/readonly:
firmware
vendor

/vendor/rfs/mdm/mpss/readonly/vendor:
firmware

/vendor/rfs/mdm/slpi:
hlos
ramdumps
readonly
readwrite
shared

/vendor/rfs/mdm/slpi/readonly:
firmware

/vendor/rfs/mdm/tn:
hlos
ramdumps
readonly
readwrite
shared

/vendor/rfs/mdm/tn/readonly:
firmware

/vendor/rfs/msm:
adsp
cdsp
mpss
slpi

/vendor/rfs/msm/adsp:
hlos
ramdumps
readonly
readwrite
shared

/vendor/rfs/msm/adsp/readonly:
firmware
vendor

/vendor/rfs/msm/adsp/readonly/vendor:
firmware

/vendor/rfs/msm/cdsp:
hlos
ramdumps
readonly
readwrite
shared

/vendor/rfs/msm/cdsp/readonly:
firmware
vendor

/vendor/rfs/msm/cdsp/readonly/vendor:
firmware

/vendor/rfs/msm/mpss:
hlos
ramdumps
readonly
readwrite
shared

/vendor/rfs/msm/mpss/readonly:
firmware
vendor

/vendor/rfs/msm/mpss/readonly/vendor:
firmware

/vendor/rfs/msm/slpi:
hlos
ramdumps
readonly
readwrite
shared

/vendor/rfs/msm/slpi/readonly:
firmware
vendor

/vendor/rfs/msm/slpi/readonly/vendor:
firmware

**Comment by redfeast** [comment]
use adb to pull it, it exists but permissiom will be denied to list using apps in phone

**Comment by redfeast** [comment]
also send me the file please, once you pull it, to redfeastred@gmail.com

**Comment by hbarsaiyan** [comment]
adb pull /vendor/lib64/libapplypatch_jni.so
remote object '/vendor/lib64/libapplypatch_jni.so' does not exist

**Comment by redfeast** [comment]
you have telegram?? gib id

**Comment by hbarsaiyan** [comment]
@americanpsychopath

**Comment by fawazahmed0** [comment]
@redfeast @hbarsaiyan Try using this:
https://drive.google.com/file/d/1DTipcIiASNNzB37hrRFLtwJ96aHjKTOy/view

**Comment by redfeast** [comment]
thanks

**Comment by bkerler** [comment]
Extract /sbin/recovery from recovery.img if libapplypatch_jni.so doesn't exist.
