### ISSUE TITLE
ozipdecrypt on realme ui

### ISSUE THREAD

**Issue by haditriw** [bkerler/oppo_ozip_decrypt#50]
C:\Users\COMPUTER 1\AppData\Local\Programs\Python\Python36>python ozipdecrypt.py RMX1821EX_11_OTA_1100_all_GQu4ppXhf2JQ.ozip
Traceback (most recent call last):
  File "ozipdecrypt.py", line 12, in <module>
    from docopt import docopt
ModuleNotFoundError: No module named 'docopt'

C:\Users\COMPUTER 1\AppData\Local\Programs\Python\Python36>

issue while decyptozip on realme ui (based color os 7.0),, but it always work on color os 6.0 base.. any help? thanks

**Comment by bkerler** [comment]
pip3 install docopt :)

**Comment by bkerler** [comment]
As stated in the readme, "pip3 install -r requirements" solves that issue

**Comment by haditriw** [comment]
nice,, it works !
