### ISSUE TITLE
unknown aes key for realme 6 pro

### ISSUE THREAD

**Issue by gleipy** [bkerler/oppo_ozip_decrypt#52]
please add aes key for realme 6 pro

**Comment by bkerler** [comment]
Hi, realme 6 pro ozip files seem to be unencrypted.

**Comment by HashimotoSakura** [comment]
How about add the aes key about Reno Ace ?The Twrp recovery seems can decrypt the ozip about Reno Ace

**Comment by bkerler** [comment]
Can you tell me the exact model number ?

Am 11. August 2020 08:26:26 MESZ schrieb "はしもと さくら" <notifications@github.com>:

**Comment by HashimotoSakura** [comment]
I can not find the .so file.may the recovery use other so to solve that.
