### ISSUE TITLE
Decrypted as folder

### ISSUE THREAD

**Issue by mit-bhalodi** [bkerler/oppo_ozip_decrypt#54]
On decrypting I got a folder containing various files. So should I just compress it and flash it?

**Comment by miftachuz** [comment]
Same here, seems lik it just extracting the ozip file

**Comment by bkerler** [comment]
Rewriting into a zip is a feature request and will be added on the next release.

**Comment by bkerler** [comment]
Should be fixed in commit 8cc89cd
