### ISSUE TITLE
ops encrypt

### ISSUE THREAD

**Issue by lupus6** [bkerler/oppo_ozip_decrypt#55]
can you add a repack option. i been working on unlocking the OP7P on t-mobile for couple months now.  and would like to rebuild the ops to flash all at once the have a partition not encrypt during the flashing.

**Comment by bkerler** [comment]
Hi, a repack option isn't planned right now.

**Comment by lupus6** [comment]
Is there a way to wright back the modem mdn before it boots. Asking becouse
when erased the rsu_pubkey is stored in the efs safe folder and it is
writen with the mbn. And cant as the folder is locked. I beleve this is the
reason we loose the sim access if the modemst1 and modemst2 is erased.
