### ISSUE TITLE
有个栽种拿你的东西盈利，让我们一起唾弃他

### ISSUE THREAD

**Issue by guofai** [bkerler/oppo_ozip_decrypt#62]
https://www.lineageos.org.cn/thread-1420-1-1.html

**Comment by bkerler** [comment]
Sorry, I don't speak chinese. Please report issues in english. Hopefully commit 8cc89cd solves your issue.

**Comment by bkerler** [comment]
Yeah, sadly that happens quite often. Thanks for reporting.
