### ISSUE TITLE
result zip file only 42 mo

### ISSUE THREAD

**Issue by rebainoor** [bkerler/oppo_ozip_decrypt#63]
result zip file only 42 mo

:\Users\Administrateur\Desktop\wOZIP2ZIP\oppo_ozip_decrypt-master>python ozipdecrypt.py CPH2179EU_11_OTA_0140_all.ozip
ozipdecrypt 1.3 (c) B.Kerler 2017-2021
Found correct AES key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Extracting compatibility.zip
Extracting oppo_engineering.new.dat.br
Extracting oppo_engineering.patch.dat
Extracting oppo_product.patch.dat
Extracting system.patch.dat
Extracting type.txt
Extracting vendor.patch.dat
Extracting version.20271.patch.dat
Extracting version.20272.patch.dat
Extracting version.20273.patch.dat
Extracting version.20274.patch.dat
Extracting version.2027A.patch.dat
Extracting version.2027B.patch.dat
Extracting version.2027C.patch.dat
Extracting version.2027D.patch.dat
Extracting version.2027E.new.dat.br
Extracting version.2027E.patch.dat
Extracting version.202A1.patch.dat
Extracting version.202A2.patch.dat
Extracting version.202A3.patch.dat
Extracting META-INF/com/android/metadata
Extracting META-INF/com/google/android/update-binary
Extracting META-INF/com/google/android/updater-script
Extracting boot.img
Decrypting C:\Users\Administrateur\Desktop\wOZIP2ZIP\oppo_ozip_decrypt-master\tmp\out
Extracting cdt_engineering.img
Decrypting C:\Users\Administrateur\Desktop\wOZIP2ZIP\oppo_ozip_decrypt-master\tmp\out
Extracting dtbo.img
Decrypting C:\Users\Administrateur\Desktop\wOZIP2ZIP\oppo_ozip_decrypt-master\tmp\out
Extracting dynamic_partitions_op_list
Extracting lk.img
Decrypting C:\Users\Administrateur\Desktop\wOZIP2ZIP\oppo_ozip_decrypt-master\tmp\out
Extracting md1img.img
Decrypting C:\Users\Administrateur\Desktop\wOZIP2ZIP\oppo_ozip_decrypt-master\tmp\out
Extracting oppo_engineering.transfer.list
Decrypting C:\Users\Administrateur\Desktop\wOZIP2ZIP\oppo_ozip_decrypt-master\tmp\out
Extracting oppo_metadata
Extracting oppo_operate_data.sh
Extracting oppo_product.new.dat.br
Extracting oppo_product.transfer.list
Decrypting C:\Users\Administrateur\Desktop\wOZIP2ZIP\oppo_ozip_decrypt-master\tmp\out
Extracting oppo_update_script.sh
Extracting preloader.img
Decrypting C:\Users\Administrateur\Desktop\wOZIP2ZIP\oppo_ozip_decrypt-master\tmp\out
Extracting preloader_emmc.img
Decrypting C:\Users\Administrateur\Desktop\wOZIP2ZIP\oppo_ozip_decrypt-master\tmp\out
Extracting preloader_ufs.img
Decrypting C:\Users\Administrateur\Desktop\wOZIP2ZIP\oppo_ozip_decrypt-master\tmp\out
Extracting scatter.txt
Extracting scp.img
Decrypting C:\Users\Administrateur\Desktop\wOZIP2ZIP\oppo_ozip_decrypt-master\tmp\out
Extracting spmfw.img
Decrypting C:\Users\Administrateur\Desktop\wOZIP2ZIP\oppo_ozip_decrypt-master\tmp\out
Extracting sspm.img
Decrypting C:\Users\Administrateur\Desktop\wOZIP2ZIP\oppo_ozip_decrypt-master\tmp\out
Extracting system.new.dat.br
Extracting system.transfer.list
Decrypting C:\Users\Administrateur\Desktop\wOZIP2ZIP\oppo_ozip_decrypt-master\tmp\out
Extracting tee.img
Decrypting C:\Users\Administrateur\Desktop\wOZIP2ZIP\oppo_ozip_decrypt-master\tmp\out
Extracting vbmeta.img
Decrypting C:\Users\Administrateur\Desktop\wOZIP2ZIP\oppo_ozip_decrypt-master\tmp\out
Extracting vbmeta_system.img
Decrypting C:\Users\Administrateur\Desktop\wOZIP2ZIP\oppo_ozip_decrypt-master\tmp\out
Extracting vbmeta_vendor.img
Decrypting C:\Users\Administrateur\Desktop\wOZIP2ZIP\oppo_ozip_decrypt-master\tmp\out
Extracting vendor.new.dat.br
Extracting vendor.transfer.list
Decrypting C:\Users\Administrateur\Desktop\wOZIP2ZIP\oppo_ozip_decrypt-master\tmp\out
Extracting version.20271.new.dat.br
Extracting version.20271.transfer.list
Decrypting C:\Users\Administrateur\Desktop\wOZIP2ZIP\oppo_ozip_decrypt-master\tmp\out
Extracting version.20272.new.dat.br
Extracting version.20272.transfer.list
Decrypting C:\Users\Administrateur\Desktop\wOZIP2ZIP\oppo_ozip_decrypt-master\tmp\out
Extracting version.20273.new.dat.br
Extracting version.20273.transfer.list
Decrypting C:\Users\Administrateur\Desktop\wOZIP2ZIP\oppo_ozip_decrypt-master\tmp\out
Extracting version.20274.new.dat.br
Extracting version.20274.transfer.list
Decrypting C:\Users\Administrateur\Desktop\wOZIP2ZIP\oppo_ozip_decrypt-master\tmp\out
Extracting version.2027A.new.dat.br
Extracting version.2027A.transfer.list
Decrypting C:\Users\Administrateur\Desktop\wOZIP2ZIP\oppo_ozip_decrypt-master\tmp\out
Extracting version.2027B.new.dat.br
Extracting version.2027B.transfer.list
Decrypting C:\Users\Administrateur\Desktop\wOZIP2ZIP\oppo_ozip_decrypt-master\tmp\out
Extracting version.2027C.new.dat.br
Extracting version.2027C.transfer.list
Decrypting C:\Users\Administrateur\Desktop\wOZIP2ZIP\oppo_ozip_decrypt-master\tmp\out
Extracting version.2027D.new.dat.br
Extracting version.2027D.transfer.list
Decrypting C:\Users\Administrateur\Desktop\wOZIP2ZIP\oppo_ozip_decrypt-master\tmp\out
Extracting version.2027E.transfer.list
Decrypting C:\Users\Administrateur\Desktop\wOZIP2ZIP\oppo_ozip_decrypt-master\tmp\out
Extracting version.202A1.new.dat.br
Extracting version.202A1.transfer.list
Decrypting C:\Users\Administrateur\Desktop\wOZIP2ZIP\oppo_ozip_decrypt-master\tmp\out
Extracting version.202A2.new.dat.br
Extracting version.202A2.transfer.list
Decrypting C:\Users\Administrateur\Desktop\wOZIP2ZIP\oppo_ozip_decrypt-master\tmp\out
Extracting version.202A3.new.dat.br
Extracting version.202A3.transfer.list
Decrypting C:\Users\Administrateur\Desktop\wOZIP2ZIP\oppo_ozip_decrypt-master\tmp\out
Extracting META-INF/com/android/otacert
Extracting META-INF/MANIFEST.MF
Extracting META-INF/CERT.SF
Extracting META-INF/CERT.RSA
DONE... files decrypted to: C:\Users\Administrateur\Desktop\wOZIP2ZIP\oppo_ozip_decrypt-master\CPH2179EU_11_OTA_0140_all.zip

C:\Users\Administrateur\Desktop\wOZIP2ZIP\oppo_ozip_decrypt-master>

**Comment by bkerler** [comment]
Hi, just verified, but it works fine. The resulting file is 1.8gb large.
