### ISSUE TITLE
Is there a simple way to repack the decrypted zip with replaced boot.img and succesfully flash it?

### ISSUE THREAD

**Issue by yunlhan** [bkerler/oppo_ozip_decrypt#65]
Hello,

Thanks for your great work!

As of now, we can use Magisk Manager to patch boot.img extracted from decrypted firmware zip (e.g., A3). Have you tried replacing the original firmware with patched boot.img, repacking it then flashing it to an Oppo device, .e.g., A3? If this could work, then we can install magisk on any Oppo device.

Thanks.

**Comment by google-mirror** [comment]
No way

**Comment by bkerler** [comment]
This would only work with resigning, but for that you need the corresponding private keys or the device needs to be unlocked first.
