### ISSUE TITLE
can't extract recovery from Reno OFP

### ISSUE THREAD

**Issue by roytam1** [bkerler/oppo_ozip_decrypt#9]
running `ofp_libextract.py CPH1917EX_11_A.05_190413_9df33f2c.ofp` gives a corrupted recovery.cpio.gz

**Comment by zhixiang520** [comment]
I can extract recovery.cpio.gz, but I am following the ghidra step.  Can
you communicate?

roytam1 <notifications@github.com> 于 2019年6月3日周一 22:47写道：

**Comment by bkerler** [comment]
If you can share a link to the ofp file, I can have a look.

**Comment by roytam1** [comment]
> If you can share a link to the ofp file, I can have a look.

http://www.mediafire.com/file/3n2ze3esc1qkqc3

**Comment by roytam1** [comment]
as a note: rev 87f0464 works with Reno OFP now.

**Comment by roytam1** [comment]
just extracted the key, but when I tried to decrypt Reno's OTA ozip, it raised an error:

````
E:\test\oppo_ozip_decrypt-master>c:\Python37-32\python.exe ozipdecrypt.py CPH1917EX_11_OTA_0080_all_GWbhnkTy2RvI.ozip
ozipdecrypt 0.4 (c) B.Kerler 2017-2019
Found correct AES key: ACAC1E13A12531AE4A1B21BB31C13C21
Decrypting...
Traceback (most recent call last):
  File "ozipdecrypt.py", line 97, in <module>
    main()
  File "ozipdecrypt.py", line 77, in main
    wf.write(ctx.decrypt(data))
  File "c:\Python37-32\lib\site-packages\Crypto\Cipher\_mode_ecb.py", line 195, in decrypt
    raise ValueError("Data must be aligned to block boundary in ECB mode")
ValueError: Data must be aligned to block boundary in ECB mode
````
ozip file size is 3,008,799,799 bytes.
dec file size is 3,008,790,528 bytes.

**Comment by roytam1** [comment]
It seems that it uses different file structure for new systems: https://oppo-au.custhelp.com/app/software_update_detail/p_name/Reno

it seems to have standard zip file structure with encrypted data
